###
POST http://localhost:1337/api/auth/local
Content-Type: application/json

{
    "data": {
        "email": "test@mail.com",
        "password": "motdepasse"
    }
}

###
POST http://localhost:1337/api/users
Content-Type: application/json

{
  "data": {
    "email": "test@mail.com",
    "password": "motdepasse"
  }
}
